server:
  port: 20000

spring:
  application:
    name: polyflow-application
  jackson:
    deserialization:
      read-date-timestamps-as-nanoseconds: true
springdoc:
  swagger-ui:
    use-root-path: true



polyflow:
  integration:
    collector:
      camunda:
        process-instance:
          enabled: false
        process-definition:
          enabled: false
        task:
          enabled: true
          enricher:
            type: processVariables
axon:
  serializer:
    general: JACKSON
    messages: JACKSON
    events: JACKSON
