server:
  port: 20002

spring:
  application:
    name: business-application


springdoc:
  swagger-ui:
    use-root-path: true

polyflow:
  integration:
    sender:
      enabled: true
      data-entry:
        enabled: true
        type: simple
