server:
  port: 20001

spring:
  application:
    name: camunda-application

camunda:
  bpm:
    login:
      enabled: true
      user-id: admin
    admin-user:
      id: admin
    filter:
      create: All
    metrics:
      enabled: false
      db-reporter-activate: false
    generic-properties:
      properties:
        initializeTelemetry: false
        telemetryReporterActivate: false

polyflow:
  integration:
    collector:
      camunda:
        application-name: ${spring.application.name}  # default
        process-instance:
          enabled: false
        process-definition:
          enabled: false
        task:
          enabled: true
          enricher:
            type: processVariables
    sender:
      enabled: true
      data-entry:
        enabled: false
        application-name: ${spring.application.name}  # default
      process-definition:
        enabled: false
      process-instance:
        enabled: false
      task:
        enabled: true
        type: tx
